spring:
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  data:
    mongodb:
      uri: mongodb+srv://<<user>>:<<pass>>@cluster0.aopulmp.mongodb.net/movies?retryWrites=true&w=majority
